### PR TITLE
Always show disable automatic welcoming button

### PR DESCRIPTION
**Pull request by DatGuy1**
Apparently I overcomplicated it. It would be good to just have a checkbox to tell if it is enabled and uncheck it to disable the feature. #261

### CODE REVIEW

**Comment by stwalkerster** [comment]
OK, so my quick testing of this has revealed a flaw in just removing the `if` statement. When a welcome template is selected, note the green styling (from `class="success"`) of the row, and the change in visual style of the selected button (from the `if` on line 106) of `templates/welcome-template/list.tpl`:

image

However, when I choose the disable option, I get this:

image

We basically need to copy the styling applied to the selected button with an appropriate condition (`== null`), and make sure it's showing the right thing. I think we can ignore the green colouring for now, as that doesn't make much UX sense on when disabled.

**Comment by DatGuy1** [comment]
I don't think I quite understand. So, if automatic welcoming is disabled, the row should have a green 'overlay' and have selected instead of select?

**Comment by stwalkerster** [comment]
@DatGuy1 yeah, something like that. Basically, at the moment, when there's no template selected, the row is hidden, so there's no need for it to change to show it's selected like all the other ones do. With your change as it is at the moment, there's nothing to show that the "disable welcoming" row is the currently selected one.

As all of the other rows have a green background, and change to a disabled "selected" button when it's the one selected, this one should do the same thing for consistency.

**Comment by stwalkerster** [comment]
@DatGuy1 this is what I meant:

image

Turns out that a quick attempt at implementing it was more problematic than I first thought, since the Bootstrap styles didn't apply to the `<tfoot>` element in HTML, so I also extended Bootstrap to add that styling.

**Pull request merged**
