### PR TITLE
Create a couple tests and fix #126

### LINKED ISSUE #126: Offer buttons to Google email or visit ISP
Should be able to Google the email address and if not the generic free hosts (Yahoo, Hotmail, Gmail, etc) should be able to navigate to the home page of the domain.

### PR DESCRIPTION
**Pull request by Matthewrbowker**
This is a real quick pull request, including functionality for issue #126 and a few basic tests.

### CODE REVIEW

**Comment by FastLizard4** [comment]
I'm inclined to reject this pull request as too heavy for master.  I think everything except maybe the fix for #126 should go into newinternal, especially anything to do with unit testing.

**Comment by Matthewrbowker** [comment]
I have already mirrored the applicable unit tests into newinternal.

**Comment by FastLizard4** [comment]
Then why do we need them here?  We are attempting to minimize activity on master while newinternal is in development, to avoid merging problems later.

**Comment by Matthewrbowker** [comment]
Erm... because I can't git very well.  Is there a way to exclude them?

**Comment by FastLizard4** [comment]
There is, I'll walk you through the process on IRC (it'll involve opening a new pull request, so I'm closing this one)

**Pull request closed without merging**
