### PR TITLE
Switch username and IP sections

### PR DESCRIPTION
**Pull request by DatGuy1**
Issue #427

### CODE REVIEW

**Comment by FastLizard4** [comment]
Why is travis failing this?

**Comment by FastLizard4** [comment]
Also, I think this change needs some discussion from the tool users about whether or not this is a good thing; see also https://xkcd.com/1172/

**Comment by stwalkerster** [comment]
From a code PoV, I think this is fine, but I want to check the UI for oddities, hence the delay in getting my dev env back online. I'm fairly sure there was consensus for this from IRC when I created the task.

As to Travis - probably something unrelated in newinternal, that's probably been fixed in newinternal-bugfixing. I'll look properly later.

**Comment by stwalkerster** [comment]
I'll also target this for either newinternal-bugfixing, or possibly even something later like rbac, but I'll look at that from my dev env.

**Pull request closed without merging**
